use chrono::{DateTime, Utc};
use mongodb::bson::oid::ObjectId;
use serde::{Deserialize, Serialize}; // Import TimeZone for creating default dates

#[derive(Default, Debug, Serialize, Deserialize)]
pub struct Site {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<ObjectId>,
    pub id: Option<String>,
    pub municipal_dsgtn: Option<String>,
    pub architect: Option<String>,
    pub integrity_envir: Option<String>,
    pub related_links: Vec<Option<String>>,
    pub master_plan_theme: Option<String>,
    pub style_crit: Option<String>,
    pub provincial_dsgtn: Option<String>,
    pub is_featured_resource: bool,
    pub significance_integrity: Option<String>,
    pub address: Option<String>,
    pub activity_crit: Option<String>,
    pub last_update_dt: DateTime<Utc>,
    pub municipal_dsgtn_dt: DateTime<Utc>,
    pub name: Option<String>,
    pub landmark_crit: Option<String>,
    pub integrity_des: Option<String>,
    pub architecture_style: Option<String>,
    pub design_crit: Option<String>,
    pub federal_dsgtn: Option<String>,
    pub significance_stmt_hist_owner: Option<String>,
    pub const_crit: Option<String>,
    pub provincial_dsgtn_dt: DateTime<Utc>,
    pub integrity_workmanship: Option<String>,
    pub person_crit: Option<String>,
    pub resource_ty: Option<String>,
    pub integrity_assoc: Option<String>,
    pub demolished_dt: Option<DateTime<Utc>>,
    pub significance_stmt_hrtg_val: Option<String>,
    pub development_era: Option<String>,
    pub municipal_url: Option<String>,
    pub legal_dscrn: Option<String>,
    pub institution_crit: Option<String>,
    pub significance_stmt_src: Option<String>,
    pub symbolic_crit: Option<String>,
    pub typology: Option<String>,
    pub picture_type: Option<String>,
    pub point: [f64; 2],
    pub integrity_loc: Option<bool>,
    pub orig_owner: Option<String>,
    pub event_crit: Option<String>,
    pub integrity_mtrl: Option<String>,
    pub significance_stmt_dscrn: Option<String>,
    pub registered_dsgtn: Option<String>,
    pub significance_stmt_char_elem: Option<String>,
    pub registered_dsgtn_dt: DateTime<Utc>,
    pub pic_url: Option<String>,
    pub federal_dsgtn_dt: DateTime<Utc>,
    pub significance_stmt_dir_search: Option<String>,
    pub comment: Option<String>,
    pub builder: Option<String>,
    pub community: Option<String>,
    pub resource_alternate_nm: Option<String>,
    pub orig_use_ty: Option<String>,
    pub significance_summ: Option<String>,
    pub integrity_stmt: Option<String>,
    pub construction_yr: Option<String>,
    pub evaluation_author: Option<String>,
}
