use chrono::{DateTime, Utc};
use mongodb::bson::oid::ObjectId;
use serde::{Deserialize, Serialize}; // Import TimeZone for creating default dates

#[derive(Default, Debug, Serialize, Deserialize)]
pub struct Site {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<ObjectId>,
    pub id: String,
    pub municipal_dsgtn: String,
    pub architect: String,
    pub integrity_envir: String,
    pub related_links: Vec<String>,
    pub master_plan_theme: String,
    pub style_crit: String,
    pub provincial_dsgtn: String,
    pub is_featured_resource: bool,
    pub significance_integrity: String,
    pub address: String,
    pub activity_crit: String,
    pub last_update_dt: DateTime<Utc>,
    pub municipal_dsgtn_dt: DateTime<Utc>,
    pub name: String,
    pub landmark_crit: String,
    pub integrity_des: String,
    pub architecture_style: String,
    pub design_crit: String,
    pub federal_dsgtn: String,
    pub significance_stmt_hist_owner: String,
    pub const_crit: String,
    pub provincial_dsgtn_dt: DateTime<Utc>,
    pub integrity_workmanship: String,
    pub person_crit: String,
    pub resource_ty: String,
    pub integrity_assoc: String,
    pub demolished_dt: Option<DateTime<Utc>>,
    pub significance_stmt_hrtg_val: String,
    pub development_era: String,
    pub municipal_url: String,
    pub legal_dscrn: String,
    pub institution_crit: String,
    pub significance_stmt_src: String,
    pub symbolic_crit: String,
    pub typology: String,
    pub picture_type: String,
    pub point: [f64; 2],
    pub integrity_loc: String,
    pub orig_owner: String,
    pub event_crit: String,
    pub integrity_mtrl: String,
    pub significance_stmt_dscrn: String,
    pub registered_dsgtn: String,
    pub significance_stmt_char_elem: String,
    pub registered_dsgtn_dt: DateTime<Utc>,
    pub pic_url: String,
    pub federal_dsgtn_dt: DateTime<Utc>,
    pub significance_stmt_dir_search: String,
    pub comment: String,
    pub builder: String,
    pub community: String,
    pub resource_alternate_nm: String,
    pub orig_use_ty: String,
    pub significance_summ: String,
    pub integrity_stmt: String,
    pub construction_yr: String,
    pub evaluation_author: String,
}
